- name: Start nzbget
  ansible.builtin.service:
    name: nzbget.service
    state: started
    enabled: true
  become: true

- name: Reload nzbget
  ansible.builtin.service:
    name: nzbget.service
    state: reloaded
    enabled: true
  become: true
