- name: start nzbget
  service:
    name: nzbget.service
    state: started
    enabled: yes
  become: yes

- name: reload nzbget
  service:
    name: nzbget.service
    state: reloaded
    enabled: yes
  become: yes
