- name: install prereqs
  package:
    name: curl
    state: present
  become: yes

- name: create cf ddns group
  group:
    name: "{{ cf_ddns_group }}"
    system: yes
    state: present
  become: yes

- name: create cf ddns user
  user:
    name: "{{ cf_ddns_user }}"
    group: "{{ cf_ddns_group }}"
    system: yes
    shell: /sbin/nologin
    state: present
  become: yes

- name: create user script dir
  file:
    path: /home/{{ cf_ddns_user }}/bin
    state: directory
    owner: "{{ cf_ddns_user }}"
    group: "{{ cf_ddns_group }}"
  become: yes

- name: copy ddns script
  template:
    src: cloudflare.sh.j2
    dest: /home/cf-ddns/bin/cloudflare.sh
    owner: "{{ cf_ddns_user }}"
    group: "{{ cf_ddns_group }}"
    mode: 0700
  become: yes
  notify: start ddns

- name: add cf ddns service file
  template:
    src: cf-ddns.service.j2
    dest: /etc/systemd/system/cf-ddns.service
  become: yes
  notify: start ddns

- name: add cf ddns timer file
  template:
    src: cf-ddns.timer.j2
    dest: /etc/systemd/system/cf-ddns.timer
  become: yes
  notify: start ddns timer
