- name: Add backports source
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release | lower }}-backports main contrib non-free"
    state: present
    update_cache: true
  become: true

- name: Install prereqs
  ansible.builtin.apt:
    update_cache: true
    name:
      - lsb-release
      - linux-headers-{{ ansible_kernel }}
    state: present
  become: true

- name: Install ZFS
  ansible.builtin.apt:
    name:
      - zfsutils-linux
      - zfs-dkms
    state: present
    default_release: "{{ ansible_distribution_release | lower }}-backports"
  become: true
