- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present
  become: true
  notify: Start nginx

- name: Install certbot prereqs
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
      - python3-venv
      - libaugeas0
    state: present
  become: true

- name: Create certbot venv
  ansible.builtin.pip:
    name: ['pip', 'setuptools']
    state: present
    virtualenv: /opt/certbot
    virtualenv_command: /usr/bin/python3 -m venv
  become: true

- name: Install certbot
  ansible.builtin.pip:
    name:
      - certbot
      - certbot-nginx
      - certbot-dns-cloudflare
    state: present
    virtualenv: /opt/certbot
  become: true

- name: Link certbot
  ansible.builtin.file:
    src: /opt/certbot/bin/certbot
    dest: /usr/bin/certbot
    state: link
  become: true

- name: Create certbot cloudflare config file
  ansible.builtin.template:
    src: credentials.ini.j2
    dest: /root/credentials.ini
    mode: '0600'
  become: true

- name: Generate certificates
  ansible.builtin.command: /opt/certbot/bin/certbot certonly --dns-cloudflare --dns-cloudflare-credentials /root/credentials.ini -d {{ nginx_domain }} -d "*.{{ nginx_domain }}" -i nginx --email "{{ nginx_certbot_email }}" --agree-tos -n
  args:
    creates: /etc/letsencrypt/live/{{ nginx_domain }}/privkey.pem
  become: true

- name: Create certbot cert update service
  ansible.builtin.template:
    src: certbot-renew.service.j2
    dest: /etc/systemd/system/certbot-renew.service
    mode: '0644'
  become: true
  notify: Enable certbot renew

- name: Create certbot cert update timer
  ansible.builtin.template:
    src: certbot-renew.timer.j2
    dest: /etc/systemd/system/certbot-renew.timer
    mode: '0644'
  become: true
  notify: Start certbot renew timer

- name: Create certbot binary update service
  ansible.builtin.template:
    src: certbot-update.service.j2
    dest: /etc/systemd/system/certbot-update.service
    mode: '0644'
  become: true
  notify: Enable certbot update

- name: Create certbot binary update timer
  ansible.builtin.template:
    src: certbot-update.timer.j2
    dest: /etc/systemd/system/certbot-update.timer
    mode: '0644'
  become: true
  notify: Start certbot update timer

- name: Remove default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Add new nginx default config
  ansible.builtin.template:
    src: nginx-default.j2
    dest: /etc/nginx/sites-available/nginx-default
    mode: '0644'
  become: true

- name: Link nginx default
  ansible.builtin.file:
    src: /etc/nginx/sites-available/nginx-default
    dest: /etc/nginx/sites-enabled/default
    state: link
  become: true
  notify: Reload nginx

- name: Add vtt proxy config
  ansible.builtin.template:
    src: vtt.j2
    dest: /etc/nginx/sites-available/vtt
    mode: '0644'
  become: true

- name: Link vtt proxy config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/vtt
    dest: /etc/nginx/sites-enabled/vtt
    state: link
  become: true
  notify: Reload nginx

- name: Add city proxy config
  ansible.builtin.template:
    src: city.j2
    dest: /etc/nginx/sites-available/city
    mode: '0644'
  become: true

- name: Link city proxy config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/city
    dest: /etc/nginx/sites-enabled/city
    state: link
  become: true
  notify: Reload nginx
