- name: Install extrepo
  ansible.builtin.package:
    name: extrepo
    state: present
  become: true

- name: Enable jellyfin repo
  ansible.builtin.command:
    cmd: extrepo enable jellyfin
    creates: /etc/apt/sources.list.d/extrepo_jellyfin.sources
  become: true

- name: Install jellyfin
  ansible.builtin.package:
    name: jellyfin
    state: present
  become: true
  notify: Start jellyfin

- name: Add jellyfin user to media group
  ansible.builtin.user:
    name: jellyfin
    groups: media
    append: true
  become: true

- name: Add jellyfin user to render group
  ansible.builtin.user:
    name: jellyfin
    groups: render
    append: true
  become: true
