- hosts: jellyfin,qbittorrent,arr,nzbget
  tasks:
    - name: Create media group
      group:
        name: media
        gid: 1000
        state: present
        system: yes
      become: yes

- hosts: jellyfin
  tasks:
    - name: Install mesa GPU drivers
      package:
        name: mesa-va-drivers
        state: present
      become: yes
  roles:
    - jellyfin

- hosts: qbittorrent
  roles:
    - qbittorrent

- hosts: arr
  roles:
    - docker
    - sonarr
    - radarr
    - bazarr
    - jackett
    - jellyseerr

- hosts: nginx
  vars:
    nginx_domain: "{{ domain }}"
    nginx_cf_token: "{{ cloudflare_token }}"
    nginx_certbot_email: "{{ email }}"
    cf_ddns_email: "{{ email }}"
    cf_ddns_key: "{{ cloudflare_token }}"
    cf_ddns_zone: "{{ cloudflare_zone }}"
    cf_ddns_record: "{{ domain }}"
  roles:
    - cf-ddns
    - nginx

- hosts: nzbget
  vars:
    nzbget_server_name: "{{ usenet_server_name }}"
    nzbget_server_host: "{{ usenet_server_host }}"
    nzbget_server_port: "{{ usenet_server_port }}"
    nzbget_server_user: "{{ usenet_username }}"
    nzbget_server_pass: "{{ usenet_password }}"
  roles:
    - nzbget

- hosts: vtt
  vars:
    foundry_domain: "vtt.{{ domain }}"
    foundry_key: # Admin key to access foundry
    foundry_download_url: # Download URL for node archive
  roles:
    - foundry

- hosts: city
  vars:
    foundry_domain: "city.{{ domain }}"
    foundry_key: # Admin key to access foundry
    foundry_download_url:  # Download URL for node archive
  roles:
    - foundry
