- hosts: all
  roles:
    - common

- hosts: pihole
  roles:
    - docker
    - pihole-compose

- hosts: pi
    - name: Install wireguard
      package:
        name: wireguard
        state: present
      become: yes
  roles:
  roles:
    - docker
    - media-server-compose
