- name: Wireguard up
  ansible.builtin.service:
    name: wg-quick@wg0
    state: started
    enabled: true
  become: true

- name: Start qbittorrent-nox
  ansible.builtin.service:
    name: qbittorrent-nox
    state: started
    enabled: true
  become: true
