- name: Install LXC
  ansible.builtin.package:
    name:
      - lxc
      - debootstrap
      - bridge-utils
      - libvirt0
      - libpam-cgfs
      - bridge-utils
      - uidmap
     # - libvirt-bin
    state: present
  become: true

- name: Install packages for host-bridge
  ansible.builtin.package:
    name:
      - libvirt-clients
      - libvirt-daemon-system
      - iptables
      - ebtables
      - dnsmasq-base
      - libxml2-utils
      - iproute2
    state: present
  become: true

- name: Copy default config
  ansible.builtin.copy:
    src: default.conf
    dest: /etc/lxc/default.conf
    mode: '0644'
  become: true

- name: Start default network
  ansible.builtin.command: virsh net-start default
  notify: Autostart virsh
  register: virsh
  failed_when:
    - virsh.rc != 0
    - '"network is already active" not in virsh.stderr'
  changed_when: virsh == 0
  become: true

- name: LXC user networking
  ansible.builtin.template:
    src: lxc-usernet.j2
    dest: /etc/lxc/lxc-usernet
    mode: '0644'
  become: true

- name: Create user config dir
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/lxc"
    state: directory
    mode: '0750'
  become: true

- name: Get user ids
  block:
    - name: Get ms uid
      ansible.builtin.shell: "set -o pipefail; grep {{ ansible_user }} /etc/subuid  | cut -d : -f 2"
      register: sh_ms_uid
      changed_when: false
    - name: Get me uid
      ansible.builtin.shell: "set -o pipefail; grep {{ ansible_user }} /etc/subuid  | cut -d : -f 3"
      register: sh_me_uid
      changed_when: false
    - name: Get ms gid
      ansible.builtin.shell: "set -o pipefail; grep {{ ansible_user }} /etc/subgid  | cut -d : -f 2"
      register: sh_ms_gid
      changed_when: false
    - name: Get me gid
      ansible.builtin.shell: "set -o pipefail; grep {{ ansible_user }} /etc/subgid  | cut -d : -f 3"
      register: sh_me_gid
      changed_when: false

- name: Template user config
  ansible.builtin.template:
    src: default.conf.j2
    dest: "{{ lookup('env', 'HOME') }}/.config/lxc/default.conf"
    mode: '0644'
  become: true

- name: Allow lingering sessions
  ansible.builtin.command: loginctl enable-linger {{ ansible_user }}
  become: true
