- name: Install wireguard
  ansible.builtin.package:
    name:
      - wireguard
      - openresolv
    state: present
  become: true

- name: Copy wireguard conf
  ansible.builtin.template:
    source: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0644'
  become: true
  notify: Wireguard up

- name: Create qbittorrent group
  ansible.builtin.group:
    name: "{{ qbittorrent_group }}"
    system: true
    state: present
  become: true

- name: Create qbittorrent user
  ansible.builtin.user:
    name: "{{ qbittorrent_user }}"
    group: "{{ qbittorrent_group }}"
    groups: media
    system: true
    shell: /sbin/nologin
    append: true
    state: present
  become: true

- name: Install qbittorrent-nox
  ansible.builtin.package:
    name: qbittorrent-nox
    state: present
  become: true

- name: Template qbittorrent-nox systemd service file
  ansible.builtin.template:
    source: qbittorrent-nox.service.j2
    dest: /etc/systemd/system/qbittorrent-nox.service
    mode: '0644'
  become: true
  notify: Start qbittorrent-nox
