- name: Check if Sonarr is installed
  ansible.builtin.stat:
    path: /opt/Sonarr/Sonarr
  register: stat_sonarr

- name: Create sonarr user
  ansible.builtin.user:
    name: sonarr
    group: media
    system: true
    shell: /sbin/nologin
    state: present
  become: true

- name: Create directories
  ansible.builtin.file:
    path: /var/lib/sonarr
    owner: sonarr
    group: media
    state: directory
    mode: '0755'
  become: true

- name: Install prereqs
  ansible.builtin.package:
    name:
      - curl
      - sqlite3
      - wget
    state: present
  become: true

- name: Get sonarr
  ansible.builtin.get_url:
    url: https://services.sonarr.tv/v1/download/main/latest?version={{ sonarr_version }}&os=linux&arch=x64
    dest: /tmp/sonarr.{{ sonarr_version }}.linux.tar.gz
    mode: '0644'
  when: not stat_sonarr.stat.exists

- name: Unarchive sonarr
  ansible.builtin.unarchive:
    src: /tmp/sonarr.{{ sonarr_version }}.linux.tar.gz
    remote_src: true
    owner: sonarr
    group: media
    dest: /opt/
    creates: /opt/Sonarr/Sonarr
  become: true
  when: not stat_sonarr.stat.exists
  notify: Start sonarr

- name: Remove sonarr download
  ansible.builtin.file:
    path: /tmp/sonarr.{{ sonarr_version }}.linux.tar.gz
    state: absent
  become: true

- name: Template sonarr
  ansible.builtin.template:
    src: sonarr.service.j2
    dest: /etc/systemd/system/sonarr.service
    mode: '0644'
  become: true
  notify: Start sonarr
