- name: Check if Sonarr is installed
  stat:
    path: /opt/Sonarr/Sonarr
  register: stat_sonarr

- name: Create sonarr user
  user:
    name: sonarr
    group: media
    system: yes
    shell: /sbin/nologin
    state: present
  become: yes

- name: Create directories
  file:
    path: /var/lib/sonarr
    owner: sonarr
    group: media
    state: directory
  become: yes

- name: Install prereqs
  package:
    name:
      - curl
      - sqlite3
      - wget
    state: present
  become: yes

- name: Get sonarr
  get_url:
    url: https://services.sonarr.tv/v1/download/main/latest?version={{ sonarr_version }}&os=linux&arch=x64
    dest: /tmp/sonarr.{{ sonarr_version }}.linux.tar.gz
  when: not stat_sonarr.stat.exists

- name: Unarchive sonarr
  unarchive:
    src: /tmp/sonarr.{{ sonarr_version }}.linux.tar.gz
    remote_src: yes
    owner: sonarr
    group: media
    dest: /opt/
    creates: /opt/Sonarr/Sonarr
  become: yes
  when: not stat_sonarr.stat.exists
  notify: start sonarr

- name: Template sonarr
  template:
    src: sonarr.service.j2
    dest: /etc/systemd/system/sonarr.service
    mode: 0664
  become: yes
  notify: start sonarr
