- name: Check if bazarr is installed
  ansible.builtin.stat:
    path: /opt/bazarr/bazarr.py
  register: stat_bazarr

- name: Create bazarr user
  ansible.builtin.user:
    name: bazarr
    group: media
    system: true
    shell: /sbin/nologin
    state: present
  become: true

- name: Install prereqs
  ansible.builtin.package:
    name:
      - unzip
      - python3-dev
      - python3-pip
      - python3-distutils
      - python3-venv
    state: present
  become: true

- name: Download bazarr
  ansible.builtin.get_url:
    url: https://github.com/morpheus65535/bazarr/releases/latest/download/bazarr.zip
    dest: /tmp/bazarr.zip
    mode: '0644'
  when: not stat_bazarr.stat.exists

- name: Create directories
  ansible.builtin.file:
    path: /opt/bazarr
    owner: bazarr
    group: media
    state: directory
    mode: '0644'
  become: true

- name: Unarchive bazarr
  ansible.builtin.unarchive:
    src: /tmp/bazarr.zip
    remote_src: true
    dest: /opt/bazarr
    owner: bazarr
    group: media
    creates: /opt/bazarr/bazarr.py
  become: true
  when: not stat_bazarr.stat.exists
  notify: Start bazarr

- name: Create virtual env for bazarr
  ansible.builtin.pip:
    name: ['pip', 'setuptools']
    state: present
    virtualenv: /opt/bazarr/venv
    virtualenv_command: /usr/bin/python3 -m venv
  become: true
  become_user: bazarr

- name: Install bazarr reqs
  ansible.builtin.pip:
    requirements: /opt/bazarr/requirements.txt
    virtualenv: /opt/bazarr/venv
  become: true
  become_user: bazarr

- name: Create bazarr service file
  ansible.builtin.template:
    src: bazarr.service.j2
    dest: /etc/systemd/system/bazarr.service
    mode: '0644'
  become: true
  notify: Start bazarr
