- name: Create server dir
  file:
    path: /opt/media-server
    state: directory
    owner: "{{ media_server_user }}"
    group: "{{ media_server_group }}"
  become: yes

- name: Add docker-compose file
  template:
    src: compose.yml.j2
    dest: /opt/media-server/docker-compose.yml
    owner: '{{ media_server_user }}'
    group: '{{ media_server_group }}'
    mode: 0600
  become: yes
  notify: restart media-server

- name: Add systemd service file
  template:
    src: media-server.service.j2
    dest: /etc/systemd/system/media-server-compose.service
  become: yes
  notify: restart media-server

- name: Enable media-server
  systemd:
    name: media-server-compose.service
    enabled: yes
    daemon_reload: yes
  become: yes
