- name: Create mount point
  file:
    path: /mnt/jellydata
    state: directory
    owner: "{{ media_server_user }}"
    group: "{{ media_server_group }}"
    mode: 0775
  become: yes

- name: Mount external hdd
  ansible.posix.mount:
    path: /mnt/jellydata
    src: 'LABEL={{ media_server_dev_label }}'
    fstype: '{{ media_server_fstype }}'
    opts: defaults,auto,user,nofail,noatime
    state: mounted
  become: yes
