- name: Create pihole folder
  file:
    path: /opt/pihole
    owner: '{{ pihole_user }}'
    group: '{{ pihole_group }}'
    state: directory
  become: yes

- name: Add docker-compose file
  template:
    src: compose.yml.j2
    dest: /opt/pihole/docker-compose.yml
    owner: '{{ pihole_user }}'
    group: '{{ pihole_group }}'
    mode: 0600
  become: yes
  notify: restart pihole

- name: Add systemd service file
  template:
    src: pihole.service.j2
    dest: /etc/systemd/system/pihole-compose.service
  become: yes
  notify: restart pihole

- name: Enable pihole
  systemd:
    name: pihole-compose.service
    enabled: yes
    daemon_reload: yes
  become: yes
