- name: Disable ssh remote root login
  ansible.builtin.lineinfile:
    dest: "{{ common_ssh_sshd_config }}"
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart sshd
  become: true

- name: Disable root login
  ansible.builtin.user:
    name: root
    password: ''
  become: true

- name: Enable ssh strict mode
  ansible.builtin.lineinfile:
    dest: "{{ common_ssh_sshd_config }}"
    regexp: "^#?StrictModes"
    line: "StrictModes true"
    state: present
  notify: Restart sshd
  become: true

- name: Disable X11 forwarding
  ansible.builtin.lineinfile:
    dest: "{{ common_ssh_sshd_config }}"
    regexp: "^#?X11Forwarding"
    line: "X11Forwarding no"
    state: present
  notify: Restart sshd
  become: true

- name: Disable ssh password login
  ansible.builtin.lineinfile:
    dest: "{{ common_ssh_sshd_config }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?ChallengeResponseAuthentication"
      line: "ChallengeResponseAuthentication no"
    - regexp: "^#?UsePAM"
      line: "UsePAM no"
    - regexp: "^#?PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"
  notify: Restart sshd
  become: true

- name: Install unattened upgrades
  ansible.builtin.package:
    name: unattended-upgrades
    state: present
  become: true
  notify: Start unattended-upgrades
