- name: Install prereqs
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
      - python3
      - python3-pip
      - python3-debian
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Add Docker Module Repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    state: present
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-buildx-plugin
    state: present
  become: yes
  notify: start docker

- name: add user to docker group
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
  become: yes
