- name: Install prereqs
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Add apt key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Get architecture
  command: dpkg --print-architecture
  register: arch_cmd
  when: ansible_os_family == "Debian"
  changed_when: false

- name: Add apt repo
  apt_repository:
    repo: "deb [arch={{ arch_cmd.stdout | trim }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: yes
  when: ansible_os_family == "Debian"

- name: Install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-compose
    state: present
  become: yes
  notify: start docker

- name: add user to docker group
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
  become: yes
