- name: Check if docker is installed
  ansible.builtin.command: which docker
  register: wdocker
  ignore_errors: true
  changed_when: false

- name: Only run "update_cache=true" if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: wdocker.rc == 1

- name: Download install script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0750'
  when: wdocker.rc == 1

- name: Run install script
  ansible.builtin.shell: /tmp/get-docker.sh
  become: true
  when: wdocker.rc == 1
  notify: Start docker

- name: Install packages needed for docker-compose
  ansible.builtin.package:
    name:
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3
      - python3-pip
    state: present
  become: true

- name: Install docker-compose
  ansible.builtin.pip:
    name: docker-compose
    executable: pip3
    state: present
  become: true
