- name: Check if docker is installed
  command: which docker
  register: wdocker
  ignore_errors: yes
  changed_when: false

- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: wdocker.rc == 1

- name: Download install script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: 0770
  when: wdocker.rc == 1

- name: Run install script
  shell: /tmp/get-docker.sh
  become: yes
  when: wdocker.rc == 1
  notify: start docker

- name: Install packages needed for docker-compose
  package:
    name:
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3
      - python3-pip
    state: present
  become: yes

- name: Install docker-compose
  pip:
    name: docker-compose
    executable: pip3
    state: present
  become: yes
